
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ChildProps } from "@/types";
import { ReduxProvider } from "@/store/provider";
import { I18nProvider } from "@/lib/i18n/i18nProvider";




const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin-ext']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildProps) {
 
  return (
    <html lang='uz'>
      <body
        className={` ${dmSans.variable} antialiased overflow-x-hidden`}
      >
        <ReduxProvider>
          <I18nProvider>
            {children}
          </I18nProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
